spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: docker
    url: jdbc:mysql://127.0.0.1:3306/practice
    username: docker
  redis:
    cluster:
      nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
      max-redirects: 9
 